environment:
    RDS_HOST: ENC[AES256_GCM,data:543H4edgkQoTPaHqZa2lKVyUuLOWUQ==,iv:eIsggjcxvCIPqAjLbu7KMxyb6vMnmIWCPy4+3j9mNGo=,tag:NCLNmJ8TvKeeKJ/xywyCpw==,type:str]
    RDS_USERNAME: ENC[AES256_GCM,data:yNCM5e4wci+smdTo985NOBzGeyBgHJfGYQ==,iv:bssTt5jjsriSCnjLIywxa9xml0EOYPcqyYPtWlEAOYU=,tag:ZfS01vdGJYV2+J6LZrR+YA==,type:str]
    RDS_PASSWORD: ENC[AES256_GCM,data:1iZP91LlsitHbGNPdS5Yg36zF3JpBueJ5A==,iv:et/QY8WAFcPrxEFzWCIAduYT5vUlbjSrv8liq2H6ceA=,tag:YCx/DSo0jQS6xEM6rGu9DQ==,type:str]
    RDS_PORT: ENC[AES256_GCM,data:UncDuj2uIQ601ZBmyZG1trUOyS7J,iv:as7R/zXB8KDyuBrRdZl68+f0oSIxv0hL6Uoa2eT9gic=,tag:ZoGdxOcDg0x5eMuSbSA3lw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:412088913008:alias/lightlytics-kms-preproduction
          created_at: "2023-02-13T09:41:25Z"
          enc: AQICAHj5j/eJFqC6O7WiHI/Qj6k54uswZ54RfskXkOtyV8ojgQE+PPanSP+kuGtDmgdnH+cqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUXA3pLAQbE/216B0AgEQgDt00yGvcCsLjJR3b7WdNU6i5/7ZEh3H3QiD9VaGOywgxAXwjNOQAkGe2Lwy0vgor/4Nn+dOuqzHzdocpQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-13T09:41:34Z"
    mac: ENC[AES256_GCM,data:2pPIMTBalE0aq4ZCZ5m9+KBSyu0vBGogIJ1oPP72jzhBkypN3EqWThSGNg2dO6piDz5wPTVa8rwzfbrAWSXF8HZYJBUn7xo2C/Y+not5KfY+T+RCH1qMyG5a+YaERtBtCrC7aHvr71lP5ZkAAZCtq4nffhNIjeVsyoySYEizur8=,iv:iX48q3mTuT14Wlo2UFAdsqnlTIVv4hGcmtVi3JxNzeI=,tag:L+s0GiZOkrUwhA4Ln5i3Ig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
