environment:
    RDS_HOST: ENC[AES256_GCM,data:kaYaglCEAi4TTlLUM+I7pfAspA+0ObFpWQag8mdiKmxKYCnGbMoczrMJVeWPUgp8JVqHWAH4Srs=,iv:my/UI8Awi9D6CBfLCq4CL+u9UdIClloaCkOlxl+okfU=,tag:AaY+tNUk8bbDWdIQeOoWkQ==,type:str]
    RDS_Password: ENC[AES256_GCM,data:4ee1cn2YHquV1EWGYyXsJpm3an0=,iv:vhdK8raxEqWipXmWntwBpbXFFh5+XOdARiXq6E9Kiqk=,tag:Dl8gQ0H8wvbtoKmkcIhCjQ==,type:str]
    RDS_USERNAME: ENC[AES256_GCM,data:zDhGAJ4=,iv:wDgZ2Sww33/T/vGcTjhF608LuZl6gblyoAa33WHpjZY=,tag:nI0B6dkTTdXFCimLdAxLYg==,type:str]
    RDS_PORT: ENC[AES256_GCM,data:WxSf1w==,iv:85p5ueNi/QPFXVDxWJqNBoSmvhMRcS8dfYkyDrx4DZg=,tag:vCsQr0i5HnUYf84FofHXZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:412088913008:alias/lightlytics-kms-demo
          created_at: "2023-02-12T00:11:43Z"
          enc: AQICAHhT++a7iyJNcrUqaq3KUopXuVIndrwU80zpR30rebC9JgH0/GOqpi17mIH4+3qWMKBrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvOacETy0ymu/z7izAgEQgDvNif7WdiOm69IIDRnDxEvF1bs47a41/gv0HMuOUPMegjN9+6mh9bT6GWOty2iy4YUuc7w9lwxtpT9Hxw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-12T02:11:36Z"
    mac: ENC[AES256_GCM,data:sKMyvRQZ3y6sVblTaNgy5MDShQ+frjx5BvE8QZlnm3BwvkDyNgz2aJBEFKzYKvPP7DJyBTzIuA7KdRLCJnneG1IakLEAbKLUMvwKPWyJfY31R9UU1s3yI5IDUuQGV1y5k3qHMxHe1VpMjjERH31c8u1EFPIdNcKSu+zbGzTNF+4=,iv:Fe2W9xPJbd0DzbTgtQCm9o3q3JDw5RCLgoRjqCt7r50=,tag:OhX6MOAk7O+8C4Mzp5Z7jA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
